C_UCT = 0.7

# Tuned through paired MCTS-vs-heuristic benchmarks; keep perf defaults in sync.
DEFAULT_ITERS = 250
DEFAULT_ROLLOUT_DEPTH = 3
DEFAULT_MAX_CANDIDATE_MOVES = 5
DEFAULT_MAX_INTERRUPT_MOVES = 2
DEFAULT_PRUNING_STRATEGY = "global"
DEFAULT_MAX_SEARCH_SECONDS = 5.0
